### ISSUE TITLE
Probably wrong ts typings when creating a ride

### ISSUE THREAD

**Issue by lcallarec** [Cocolis-1/cocolis-js#8]
Hey,

It looks like there are some typos in [rides/types.ts](https://github.com/Cocolis-1/cocolis-js/blob/develop/src/rides/types.ts) :

According to Cocolis' docs :

* `from_lgn` should be named `from_lng`
* `to_lgn` should be named `to_lng`
* `photos_url` should be named `photo_urls`

Thanks !

**Comment by sebfie** [comment]
Thank you, @btnalexandre will manage that and make a PR for that !

**Comment by sebfie** [comment]
C'est corrigé dans la 1.1.0 via #9 Merci
